title: Chen Huang' Blog
description: A technical blog for writing and note-taking.
author: Chen Huang
avatar: /icon2.jpeg
email: toocold@foxmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
#  - jekyll-theme-hamilton
 

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ChenHuangPolicy
  card: summary
logo: logo.png
social:
  name: Chen Huang
  links:
skin: daylight
#    - https://twitter.com/ngzhio
#    - https://www.facebook.com/ngzhio
#    - https://github.com/ngzhio
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
